apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: demo-app-project
  source:
    repoURL: https://github.com/t-matsu200/argo-rollouts-bluegreen-demo.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc:443
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated: {}
