apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-preview-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      listen 8080;
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /demo-app-preview
        pathType: Prefix
        backend:
          service:
            name: demo-app-preview
            port:
              name: http
              number: 80
