apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: httpd:alpine3.17
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 30
  strategy:
    blueGreen:
      activeService: demo-app
      previewService: demo-app-preview
      previewReplicaCount: 1
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600
